version: '3'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
       - ./docker/db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: example

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

  web:
    build:
      context: ./
      dockerfile: docker/web.Dockerfile
    ports:
      - 80:80
    volumes:
      - ./src:/var/www/html
    links:
      - db